name: OptiBot Daily Scraper

on:
  schedule:
    # Runs daily at 9:00 AM UTC (4:00 PM Vietnam)
    - cron: "0 9 * * *"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download previous config (if exists)
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: optibot-config
          path: .

      - name: Run OptiBot scraper
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ZS_SUBDOMAIN: optisignshelp
        run: |
          python main.py

      - name: Upload config for next run
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: optibot-config
          path: optibot_config.json
          retention-days: 90

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: scraper-logs-${{ github.run_number }}
          path: |
            *.log
            article_metadata.json
          retention-days: 30
